server:
  port: 3344 #port
spring:
  application:
    name: spring-cloud-config-center # service name
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dustwh/springcloud-config.git
          # repo name
          search-paths:
            - springcloud-config
          force-pull: true
          # if Gitrepo is piblicï¼Œthen no need for username and password, othervice,username and password is needed.
          # username: ********
          # password: ********
      #branch name
      label: main
  ##### RabbitMQ related configuration, 15672 is the port of the web management interface, 5672 is the access port of MQ###########
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client: #register client to eureka list
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #register into cluster
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'